# Writes hera's R code -- packages/hera's R/*.R, NAMESPACE and DESCRIPTION -- into a C++ source file, so the kernel
# carries it and loads it at start-up without anything to install (see elara/r/hera_sources.hpp and the loader in
# interpreter_r.cpp). Run at build time, whenever one of those files changes:
#
#   cmake -DHERA_DIR=<packages/hera> -DOUTPUT=<file.cpp> -P EmbedHera.cmake
#
# Each file is a byte array, not a string literal: MSVC limits string literals to 64 KB, and bytes need no escaping.

if (NOT HERA_DIR OR NOT OUTPUT)
    message(FATAL_ERROR "EmbedHera.cmake needs -DHERA_DIR=... and -DOUTPUT=...")
endif ()

file(GLOB r_files RELATIVE "${HERA_DIR}" "${HERA_DIR}/R/*.R")
list(SORT r_files) # the order R itself sources a package's files in (no Collate field)
set(files ${r_files} NAMESPACE DESCRIPTION)

set(arrays "")
set(entries "")
set(index 0)
foreach (file IN LISTS files)
    file(READ "${HERA_DIR}/${file}" hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(APPEND arrays "const unsigned char file${index}[] = {${bytes}0x00};\n")
    string(APPEND entries "        {\"${file}\", std::string(reinterpret_cast<const char *>(file${index}), sizeof file${index} - 1)},\n")
    math(EXPR index "${index} + 1")
endforeach ()

set(content "// Generated by cmake/EmbedHera.cmake from packages/hera -- do not edit.
#include \"elara/r/hera_sources.hpp\"

namespace elara
{
    namespace hera
    {
        namespace
        {
${arrays}        }

        const std::vector<SourceFile> &sourceFiles()
        {
            static const std::vector<SourceFile> files = {
${entries}            };
            return files;
        }
    }
}
")

# rewritten only when it changes, so an unchanged hera doesn't recompile the kernel
if (EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if (previous STREQUAL content)
        return()
    endif ()
endif ()
file(WRITE "${OUTPUT}" "${content}")
